### PR TITLE
Update selector labels for Deployment and Service

### LINKED ISSUE #140: Helm Chart Upgrades Fail due to immutable selector fields in deployment.
I believe a bug was introduced in #115 when the selector fields were upgraded to use `{{- include "version-checker.labels" . | nindent 6 }}`. This is because `version-checker.labels` includes things like `app.kubernetes.io/version` which changes on newer versions. The selector field is immutable in Deployments and shouldn't change between the same release. 

To replicate:

```bash
$ helm upgrade -i version-checker jetstack/version-checker --version v0.3.1
Release "version-checker" does not exist. Installing it now.
NAME: version-checker
LAST DEPLOYED: Mon Dec  4 15:49:49 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

$ helm upgrade -i version-checker jetstack/version-checker --version v0.3.2
Error: UPGRADE FAILED: cannot patch "version-checker" with kind Deployment: Deployment.apps "version-checker" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"version-checker", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"version-checker", "app.kubernetes.io/version":"v0.3.2", "helm.sh/chart":"version-checker-v0.3.2"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

### PR DESCRIPTION
**Pull request by logand22**
Changes selector labels to not change per helm release to fix #140. These new selectors are more similar to https://github.com/cert-manager/cert-manager/blob/202a80e2184b1b479dbb5d03f32aafc4b2c811b9/deploy/charts/cert-manager/templates/service.yaml#L13-L14. 

This might require a major version bump of helm chart version because it will also cause issues when upgrading to this.

### CODE REVIEW

**Comment by davidcollom** [comment]
I agree that this is a breaking change - but the helm chart and application version are still on a `0.x` release basis which should be infured as "beta" or unstable in some respect.

I feel that the right approach was to move to the helper method over defining the labels multiple times being much more error-prone

**Comment by logand22** [comment]
> I agree that this is a breaking change - but the helm chart and application version are still on a 0.x release basis which should be infured as "beta" or unstable in some respect.

Understandable.

**Comment by logand22** [comment]
> I feel that the right approach was to move to the helper method over defining the labels multiple times being much more error-prone. 

Would you suggest removing this line then to reduce repetition but still fix the issue? 
https://github.com/jetstack/version-checker/blob/e3502202046823d07ef8bd60b7eb542b23d4eaad/deploy/charts/version-checker/templates/_helpers.tpl#L21

**Comment by davidcollom** [comment]
> > I feel that the right approach was to move to the helper method over defining the labels multiple times being much more error-prone.
> 
> Would you suggest removing this line then to reduce repetition but still fix the issue?
> 
> https://github.com/jetstack/version-checker/blob/e3502202046823d07ef8bd60b7eb542b23d4eaad/deploy/charts/version-checker/templates/_helpers.tpl#L21

Yea, sure - I'd accept a PR with that line removed! 👍

**Comment by logand22** [comment]
Ended up creating a separate helper instead since I think having the `helm.sh/chart` is actually helpful outside of the selector templates since it describes the version of the helm chart. 

Let me know if you have any more concerns.

**Review by davidcollom — APPROVED** [review]
I like that approach much better 👍

**Pull request merged**
